services:
  test_db:
    image: postgres:latest
    container_name: patrigma_test_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U testuser -d testdb -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
