name: Accessibility Test
on: [push]

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker Compose
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          docker-compose -f docker-compose.dev.yml up -d  # Start services in detached mode
          
          # Wait for services to be ready (adjust as needed)
          echo "Waiting for services to be ready..."
          sleep 30

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse Accessibility Tests
        run: |
          xvfb-run lighthouse http://localhost:3000 --output json --output-path ./lighthouse-report.json --only-categories=accessibility
          xvfb-run lighthouse http://localhost:3000 --output html --output-path ./lighthouse-report.html --only-categories=accessibility

      - name: Upload Lighthouse Report JSON
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report-json
          path: ./lighthouse-report.json

      - name: Upload Lighthouse Report HTML
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report-html
          path: ./lighthouse-report.html

      - name: Extract Accessibility Score
        run: |
          node -e "
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('./lighthouse-report.json', 'utf8'));
            const score = report.categories.accessibility.score * 100;
            console.log('Accessibility Score:', score);
            if (score < 90) {
              process.exit(1);
            }
          "
