name: Build, Test, and Publish
run-name: Publish Docker image

on:
  push:
    branches:
      - tesci


jobs:
  test-app:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-docker-prod:
    runs-on: ubuntu-latest
    needs: test-app
    if: github.ref_name == 'tesci' || github.ref_type == 'tag'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/my-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  notify:
    runs-on: ubuntu-latest
    needs: build-docker-prod
    steps:
      - name: Shoutrrr
        uses: containrrr/shoutrrr-action@v1
        with:
          url: ${{ secrets.NOTIF_URL }}
          title: Deployed ${{ github.sha }} on server
          message: See changes at ${{ github.event.compare }}.
