name: Build, Test, Release, and Publish
run-name: Release and Publish Docker image

on:
  push:
    branches:
      - tesci

env:
  VERSION: ""  # Définition initiale de la variable
  REPO_OWNER: ""  # Variable pour stocker le nom du propriétaire du repo en minuscules

jobs:
  test-app:
    name: Test App
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-docker-prod:
    runs-on: ubuntu-latest
    needs: test-app
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER }}/patrigma:v${{ env.VERSION }}
          labels: "version=${{ env.VERSION }},commit=${{ github.sha }}"

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-docker-prod
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          draft: false
          prerelease: false
          body: |
            Docker image for this release: ghcr.io/${{ env.REPO_OWNER }}/patrigma:v${{ env.VERSION }}

  notify:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Notify Discord on failure
        if: always()  # Exécutez toujours cette étape, que les étapes précédentes échouent ou réussissent
        uses: containrrr/shoutrrr-action@v1
        with:
          url: ${{ secrets.NOTIFICATION_URL }}
          title: "Build Failed or Succeeded for Release v${{ env.VERSION }}"
          message: |
            The build for release v${{ env.VERSION }} may have failed or succeeded.
            Commit message: ${{ github.event.head_commit.message }}
            Commit SHA: ${{ github.sha }}
            Check the build logs for details.
