name: Build, Test, Release, and Publish
run-name: Release and Publish Docker image

on:
  push:
    branches:
      - tesci

jobs:
  test-app:
    name: Test App
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(jq -r .version package.json)"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          release_name: "Release v${{ steps.get_version.outputs.version }}"
          draft: false
          prerelease: false

  build-docker-prod:
    runs-on: ubuntu-latest
    needs: [test-app, create_release]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/patrigma:v${{ steps.get_version.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  notify:
    runs-on: ubuntu-latest
    needs: build-docker-prod
    steps:
      - name: Notify Discord on failure
        if: failure()
        uses: containrrr/shoutrrr-action@v1
        with:
          url: ${{ secrets.NOTIFICATION_URL }}
          title: "Build Failed for Release v${{ steps.get_version.outputs.version }}"
          message: |
            The build for release v${{ steps.get_version.outputs.version }} has failed.
            Commit message: ${{ github.event.head_commit.message }}
            Commit SHA: ${{ github.sha }}
      - name: Notify Discord on success
        if: success()
        uses: containrrr/shoutrrr-action@v1
        with:
          url: ${{ secrets.NOTIFICATION_URL }}
          title: "Build Succeeded for Release v${{ steps.get_version.outputs.version }}"
          message: |
            The build for release v${{ steps.get_version.outputs.version }} was successful.
            Commit message: ${{ github.event.head_commit.message }}
            Commit SHA: ${{ github.sha }}
            The Docker image has been published.
