name: Build the app and run tests
run-name: ${{ github.actor }} is creating a pull request
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate report
        run: |
          npm test
        continue-on-error: true  # Allow the job to continue even if tests fail

      - name: Upload test reports
        if: always()  # Always run this step to ensure artifacts are uploaded
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            ./test-report.html
            ./reports/junit/js-test-results.xml

      - name: Notify Discord on failure
        if: failure()  # Only run this step if the previous steps fail
        uses: containrrr/shoutrrr-action@v1
        with:
          url: ${{ secrets.NOTIFICATION_URL }}
          title: "Build failed for ${{ github.actor }}"
          message: |
            Build failed or tests did not pass
            Pull request: ${{ github.event.pull_request.html_url }}

  test-report:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # Always run this job to ensure reports are published
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download test reports
        uses: actions/download-artifact@v3
        with:
          name: test-reports

      - name: Publish test results
        uses: dorny/test-reporter@v1
        with:
          name: Jest tests
          path: ./reports/junit/js-test-results.xml
