name: Build the app and run tests
run-name: ${{ github.actor }} is creating a pull request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Notify Discord on failure
        if: failure()
        uses: containrrr/shoutrrr-action@v1
        with:
          url: ${{ secrets.NOTIFICATION_URL }}
          title: "Build failed for ${{ github.actor }}"
          message: |
              Build failed or tests did not pass
              Pull request: ${{ github.event.pull_request.html_url }}
